import React from "react";

const LandManagement = () => {
  return (
    <div>
      <h1>Land Management. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illo corrupti, dolorum nihil voluptatum laborum repudiandae id architecto exercitationem nam, quas aliquid minima eveniet dolor excepturi quisquam quia deleniti assumenda ad numquam dolores error ratione! Est asperiores assumenda adipisci deleniti molestias, atque vel maxime dolore, aspernatur commodi et praesentium cumque repellat doloribus eius, eveniet voluptates hic voluptatibus ducimus? Magni repudiandae placeat laboriosam consectetur ipsa libero impedit similique, ab atque incidunt neque delectus ullam iste vel fugiat sapiente ex saepe quam amet voluptatum! Autem alias iusto consequatur, hic omnis ad, commodi cumque, quam natus fugiat et sed dolorum. Vel aspernatur doloremque officia?</h1>
    </div>
  );
};

export default LandManagement;
